name: Bundle NeutOS

on:
  schedule: 
    - cron:  '*/60 * * * *'
  workflow_dispatch:

jobs:
  neutos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout suppository
        uses: actions/checkout@v3

      - name: Checkout SigPatches
        uses: actions/checkout@v3
        with:
          repository: borntohonk/SigPatches
          path: SigPatches

      - name: Checkout hbl
        uses: actions/checkout@v3
        with:
          repository: switchbrew/nx-hbloader
          path: hbl

      - name: Checkout hbmenu
        uses: actions/checkout@v3
        with:
          repository: switchbrew/nx-hbmenu
          path: hbmenu

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip3 install lz4

      - name: Make Loader patch
        run: cd SigPatches && python3 scripts/loader_patch.py

      - name: Put togheter Neutos bundle
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global advice.detachedHead false
          git config --global user.name 'borntohonk'
          git config --global user.email '6264306+borntohonk@users.noreply.github.com'
          AMSHASH=$(gh release view --repo github.com/Atmosphere-NX/Atmosphere --json assets --jq .assets[].url | grep -oE "\-([0-9a-f]{9})" | head -1 | cut -c2-)
          NEUTOSHASH=$(gh release view --repo github.com/borntohonk/NeutOS --json assets --jq .assets[].url | grep -oE "\-([0-9a-f]{9})" | head -1 | cut -c2-)
          if [ "$AMSHASH" = "$NEUTOSHASH" ]; then
            echo "Neutos update not needed!" && \
            exit
          else
            git clone https://github.com/Atmosphere-NX/Atmosphere.git
            sleep 10
            git -C Atmosphere checkout $AMSHASH
            AMSMAJORVER=$(grep 'define ATMOSPHERE_RELEASE_VERSION_MAJOR\b' Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
            AMSMINORVER=$(grep 'define ATMOSPHERE_RELEASE_VERSION_MINOR\b' Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
            AMSMICROVER=$(grep 'define ATMOSPHERE_RELEASE_VERSION_MICRO\b' Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
            HOS_MAJORVER=$(grep 'define ATMOSPHERE_SUPPORTED_HOS_VERSION_MAJOR\b' Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
            HOS_MINORVER=$(grep 'define ATMOSPHERE_SUPPORTED_HOS_VERSION_MINOR\b' Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
            HOS_MICROVER=$(grep 'define ATMOSPHERE_SUPPORTED_HOS_VERSION_MICRO\b' Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
            HBLVER=$(grep -P "APP_VERSION\t:=\t" hbl/Makefile | head -1 | cut -c 16-20)
            HBMENUVER=$(grep -P "export APP_VERSION\t:=\t" hbmenu/Makefile | head -1 | cut -c 23-27)
            HOSVER=$HOS_MAJORVER.$HOS_MINORVER.$HOS_MICROVER
            AMSVER=$AMSMAJORVER.$AMSMINORVER.$AMSMICROVER
            mkdir ams && \
            gh release download --repo github.com/Atmosphere-NX/Atmosphere --pattern atmosphere*.zip && \
            sleep 5 && \
            unzip atmosphere*.zip -d ams && \
            rm atmosphere*.zip && \
            mkdir updater && \
            sleep 5 && \
            cp -r SigPatches/SigPatches/atmosphere ams && \
            gh release download --repo github.com/CTCaer/hekate --pattern hekate*.zip && \
            unzip hekate*.zip -D ams && \
            rm hekate*.zip && \
            mv ams/hekate*.bin ams/hekate.bin && \
            cat SigPatches/hekate_patches/header.ini > ams/bootloader/patches.ini && \
            cat SigPatches/hekate_patches/fs_patches.ini >> ams/bootloader/patches.ini && \
            cat SigPatches/hekate_patches/loader_patches.ini >> ams/bootloader/patches.ini && \
            gh release download --repo github.com/borntohonk/aio-neutos-updater --dir ./updater && \
            sleep 5 && \
            unzip updater/aio-neutos-updater.zip -d updater && \
            cp -r updater/switch ams/
            mkdir ams/atmosphere/hosts && \
            gh release download --repo github.com/switchbrew/nx-hbloader --pattern *.nsp --dir ./ams/atmosphere/ && \
            sleep 5 && \
            mkdir hbmenu && \
            gh release download --repo github.com/switchbrew/nx-hbmenu --pattern *.zip --dir ./hbmenu && \
            sleep 5 && \
            unzip hbmenu/*.zip -d hbmenu && \
            rm hbmenu/*.zip && \
            cp hbmenu/*/*.nro ams/hbmenu.nro && \
            mkdir ams/bootloader/payloads && \
            gh release download --repo github.com/suchmememanyskill/TegraExplorer --pattern *.bin --dir ./ams/bootloader/payloads/ && \
            sleep 5 && \
            gh release download --repo github.com/shchmue/Lockpick_RCM --pattern *.bin --dir ./ams/bootloader/payloads/ && \
            sleep 5 && \
            cp ams/atmosphere/reboot_payload.bin ams/bootloader/payloads/fusee.bin && \
            cp ams/atmosphere/reboot_payload.bin ams/payload.bin && \
            cp configs/emummc.txt ams/atmosphere/hosts/emummc.txt && \
            cp configs/sysmmc.txt ams/atmosphere/hosts/sysmmc.txt && \
            cp configs/exosphere.ini ams/exosphere.ini && \
            mkdir out && \
            cd ams && \
            zip -r ../out/NeutOS-${AMSVER}-master-${AMSHASH}+hbl-${HBLVER}+hbmenu-${HBMENUVER}+patches.zip ./* && \
            cd .. && \
            sleep 5 && \
            echo "" > changelog.md && \
            echo "![Banner](https://github.com/borntohonk/NeutOS/raw/neutos/img/banner.png)" >> changelog.md && \
            echo "" >> changelog.md && \
            echo "- This release supports FW version ${HOSVER}, and sigpatches for loader, es, fs and nifm are included for this FW version." >> changelog.md && \
            echo "" >> changelog.md && \
            echo "- The payload.bin included is the latest Fusee payload from Atmosphere." >> changelog.md && \
            echo "" >> changelog.md && \
            echo "- Neutos is an Atmosphere cfw bundle maintained for myself."  >> changelog.md && \
            echo "" >> changelog.md && \
            echo "- There is an updater homebrew included now ( https://github.com/borntohonk/aio-neutos-updater )" >> changelog.md && \
            echo "" >> changelog.md && \
            echo "- Sigpatches are made and distributed at ( https://github.com/borntohonk/SigPatches ),"  >> changelog.md && \
            echo "" >> changelog.md && \
            echo "Please file an issue with the github issue tracker, if there are any inquiries." >> changelog.md && \
            echo "" >> changelog.md && \
            echo "This github and release is automated, and was published with suppository ( https://github.com/borntohonk/suppository )" >> changelog.md && \
            echo "" >> changelog.md && \
            sleep 5 && \
            gh release create $HOSVER-$AMSVER-$AMSHASH -F changelog.md out/NeutOS-${AMSVER}-master-${AMSHASH}+hbl-${HBLVER}+hbmenu-${HBMENUVER}+patches.zip --title "NeutOS $AMSVER-$AMSHASH for FW version $HOSVER" --repo github.com/borntohonk/NeutOS && \
            sleep 5 && \
            rm changelog.md
          fi
